### ISSUE TITLE
how can i run it on arm based machine such as raspberry pi and orange pi ?

### ISSUE THREAD

**Issue by bd7jat** [cypresssemiconductorco/openocd#1]
hi ,guys ,i'd like to bulid a standalone programmer based on openocd to progamme psoc4 ,but i found it can not run on pi , any suggestion for this ? I'm a fresh .Thanks so much for sharing this project, at lest it works on my pc

**Comment by ddka22** [comment]
OpenOCD usually runs fine on ARM/ARM64 but our code (PSoC4/6 and Traveo-II drivers) was never tested on anything other than PC (Win/Linux) and Mac so using ARM as a host machine is not officially supported. I will try to cross-compile the OpenOCD for Raspberry PI 4 and let you know. 
Please give us some time.

**Comment by bd7jat** [comment]
I am so so glad to receive  your response quickly ,I am right now trying to use orange  pi as an standalone programmer for psoc4 which we are preparing for  mass production. wish to have your good news .thanks so much

**Comment by ddka22** [comment]
Please find the document attached that describes the steps to use OpenOCD on Raspberry Pi to program PSoC4. 
[Raspberry Pi based OpenOCD Programmer.pdf](https://github.com/cypresssemiconductorco/openocd/files/5152065/Raspberry.Pi.based.OpenOCD.Programmer.pdf)
