### ISSUE TITLE
mxs40_reset_halt fails for RAM-based vector tables.

### ISSUE THREAD

**Issue by gtaska** [cypresssemiconductorco/openocd#2]
**Prerequisites**

Can you reproduce the problem reliably? _Yes_

Did you check current release notes for known issues? _Checked master, confirmed same logic problem exists._

If this is not the latest release, have you checked newer releases? _Checked master, confirmed same logic problem exists_

**Description**:

We have implemented a bootloader + double buffering of firmware images. Because the firmware image doesn't have a fixed location in flash to run from, it has been re-engineered so that a bootloader will copy it into RAM, and it runs from a known location there. As a result, the vector table is also now located in RAM - but OpenOCD has a hard-coded assumption that the vector table is in flash, and it refuses to set an initial breakpoint at which point most other debugging features no longer work.

**Steps to Reproduce:**

Implement bootloader and generate firmware images designed to run out of RAM, with a RAM-based vector table.

The bootloader still uses a flash-based vector table, but when the main firmware image is copied to & run out of RAM, the system switches to the RAM-based vector table. At the time OpenOCD tries to obtain the/a reset_entry address, the vector table base address has already been pointed to the RAM-based vector table.

Note: timing is also important. In systems with bootloaders that load subsequent CM0+/CM4 images, it is important to wait long enough for the last vector table address to be finalized. Ideally there should be a developer-configurable period before OpenOCD attempts to determine the reset_entry address.

**Expected Result:**

OpenOCD/mxs40_reset_halt is able to handle a RAM-based vector table and a breakpoint gets set at the User Application entry point.

**Actual Result:**

Error: "Info : Vector Table address invalid (0x08018000), reset_halt skipped"

**Frequency (1/1, 1/50, 1/100):**

5/5

**Build/Commit:**

OpenOCD included in ModusToolbox 2.1, but confirmed that the same bug occurs in master/HEAD

https://github.com/cypresssemiconductorco/openocd/blob/d526e667dedfdadead74b9ff4292344b07a5af1c/src/flash/nor/mxs40/mxs40.c#L1172

AFAIK, This problem would be solved by allowing  0x0800000 <= vt_base <= 0x08020000 (or whatever the generic top address is for the SRAM region)

**Target:**

CY8C624AAZI-S2D44

**Host OS and Version:**

ModusToolbox 2.1 on Win10.

**Compiler:**

ModusToolbox 2.1 provided gcc arm cross-compiler

**Environment**

ModusToolbox 2.1's OpenOCD used with VSCode as the IDE

**Comment by gtaska** [comment]
This only affects debugging on the Cortex-M4 core, as the Cortex-M0+ core is always running out of flash directly out of reset - even if it later jumps to a RAM-based image.

**Comment by rmbk19** [comment]
The procedure of building OpenOCD is provided in - https://github.com/cypresssemiconductorco/openocd/issues/3
