### ISSUE TITLE
kitprog3: KP3_REQUEST_ACQUIRE fails with MiniProg4 and CCG3PA

### ISSUE THREAD

**Issue by pdp7** [cypresssemiconductorco/openocd#4]
Hello, I noticed that support has been added for CCG6DF in 1ec8dc3fb0cd5b5fc1d71470b211a1a05efc70b9 by Volodymyr Medvid (@vmedcy):
https://github.com/cypresssemiconductorco/openocd/blob/d526e667dedfdadead74b9ff4292344b07a5af1c/src/flash/nor/psoc4.c#L257

I would like to program a CCG3PA part (CYPD3171-24LQXQ) using OpenOCD.  I have the MiniProg3, MiniProg4 and J-Link which I could use for the task.  I read the "CCGx (CYPDxxxx) Programming Specifications" PDF, and I am hoping that the support for CCG6DF might be able to be extended to support CCG3PA.

I am looking right now at how I could modify OpenOCD to do that, and I would very much appreciate any advice or insights you might be able to offer in regards to that.

Thank you!

**Comment by rmbk19** [comment]
Hi @pdp7, 

The query is being handled in these community threads - 
[CCG3PA: OpenOCD SWD configuration for CYPD3175?](https://community.cypress.com/t5/USB-EZ-PD-Type-C/CCG3PA-OpenOCD-SWD-configuration-for-CYPD3175/m-p/265275) 
[MiniProg4 with OpenOCD for CCG3PA?](https://community.cypress.com/t5/USB-EZ-PD-Type-C/MiniProg4-with-OpenOCD-for-CCG3PA/m-p/265272/emcs_t/S2h8ZW1haWx8Ym9hcmRfc3Vic2NyaXB0aW9ufEtLTkFETVdXUFJERzZGfDI2NTI3MnxTVUJTQ1JJUFRJT05TfGhL#M4943) 

Regards, 
Rakshith

**Comment by pdp7** [comment]
@rmbk19 
Thank you for the comment.  I am the person that posted both of those community threads but there has not been a followup reply in either thread from Cypress.

@bohdan-tymkiv @tom-van @vmedcy Would you please be able to provide any insights?  I am trying to use MiniProg4 with CCG3PA (CYPD3171-24LQXQ).  Currently, I can not get past the KP3_REQUEST_ACQUIRE USB request.  Here is OpenOCD command that I am using:
```
openocd -s ../scripts -f interface/kitprog3.cfg -f target/psoc4.cfg -c "kitprog3 power_config on 3300; kitprog3 acquire_config on 0 1 5; init; kitprog3 acquire_psoc; reset init; shutdown"
```
where `kitprog3 acquire_config on 0 1 5` means `0` for psoc4, `1` for power-cycle mode as CCG3GA lacks XRES pin and attempts is 5.  Unfortunately, 'kitprog3 acquire_psoc' fails with error code -4.  [Here is the full log](https://gist.github.com/pdp7/8ad3056959d4c626a540a9894c59bbcc).

MiniProg4 seems to receive the KP3_REQUEST_ACQUIRE usb request OK but it fails to actually run [KP3_REQUEST_ACQUIRE inside the MiniProg4 firmware succesffully](https://github.com/cypresssemiconductorco/openocd/blob/d526e667dedfdadead74b9ff4292344b07a5af1c/src/jtag/drivers/kitprog3.c#L386).  The MiniProg4 has `KitProg3: FW version: 2.10.878`.

**State of CCG3PA in Cypress applications:**
* PSoC Programmer app in Windows does work with CCG3PA using either the MiniProg3 or MiniProg4
* Cypress Programmer app _(which uses Cypress OpenOCD)_ in Windows does NOT work with CCG3PA using MiniProg4
* CypGui _(which uses Cypress OpenOCD)_ in Linux does NOT work with CCG3PA using MiniProg4

**State of CCG3PA in Cypress OpenOCD:**
* MiniProg4 and KitProg3 _(the programmer builtin to PSoC devkits)_ are discussed in the [Cypress OpenOCD CLI Guide](https://www.cypress.com/file/495061/download) along with the Cypress OpenOCD extension `kitprog3` which knows how to make USB requests to the MiniProg4/KitProg3 outside the fundamental [ARM Debug Access Port (DAP)](https://developer.arm.com/documentation/100536/0302/debug-access-port/about-the-debug-access-port?lang=en) read/write operations
> From Cypress OpenOCD: "The KitProg3/MiniProg4 (KP3/MP4) probe implements the CMSIS-DAP protocol defined by Arm with some extensions. Consequently, the KP3/MP4 driver in OpenOCD is a wrapper around the native CMSIS-DAP driver that extends its functionality with the KP3-specific extensions.
* Cypress OpenOCD claims to [support CCG6xF in `src/flash/nor/psoc4.c`](https://github.com/cypresssemiconductorco/openocd/blob/cypress/src/flash/nor/psoc4.c#L257) with https://github.com/cypresssemiconductorco/openocd/commit/1ec8dc3fb0cd5b5fc1d71470b211a1a05efc70b9 in August 2020
* I modified Cypress OpenOCD [`src/flash/nor/psoc4.c`](https://github.com/cypresssemiconductorco/openocd/blob/cypress/src/flash/nor/psoc4.c#L257) to add the silicon family ID for CCG3PA according to the [CCGx/CYPDxxxx Programming Specification](https://www.cypress.com/file/410796/download)
```diff
-- a/src/flash/nor/psoc4.c
+++ b/src/flash/nor/psoc4.c
@@ -254,6 +254,7 @@ const struct psoc4_chip_family psoc4_families[] = {
        { 0xB5, "PSoC 4100S Plus",                      .flags = 0, .spcif_ver = spcif_v3 },
        { 0xB8, "PSoC 4100S Plus/PSoC 4500",            .flags = 0, .spcif_ver = spcif_v3 },
        { 0xBE, "PSoC 4100S Max",                       .flags = 0, .spcif_ver = spcif_v3 },
+       { 0xB0, "CCG3PA USB Type-C Port Controller",    .flags = 0, .spcif_ver = spcif_v3 },
        { 0xC0, "CCG6DF USB Type-C Port Controller",    .flags = 0, .spcif_ver = spcif_v3 },
        { 0xC3, "CCG6SF USB Type-C Port Controller",    .flags = 0, .spcif_ver = spcif_v3 },
        { 0,    "Unknown",                              .flags = 0, .spcif_ver = spcif_unknown }
```
* MiniProg4/KitProg3 can connect to the DAP inside CCG3PA over SWD and read memory from the ROM table in the CCG3PA in [`psoc4_get_family()`](https://github.com/cypresssemiconductorco/openocd/blob/d526e667dedfdadead74b9ff4292344b07a5af1c/src/flash/nor/psoc4.c#L733):
```
*****************************************
** Silicon: 0x2003, Family: 0xB0, Rev.: 0x12 (A1)
** Detected Family: CCG3PA USB Type-C Port Controller
** Detected Main Flash size, kb: 64
** Chip Protection: protection OPEN
*****************************************
```
* However, the acquire process relies on Cypress OpenOCD extension in [`src/jtag/drivers/kitprog3.c`](https://github.com/cypresssemiconductorco/openocd/blob/cypress/src/jtag/drivers/kitprog3.c#L38) that are part of the [MiniProg4/KitProg3 firmware like `KP3_REQUEST_ACQUIRE`](https://github.com/cypresssemiconductorco/openocd/blob/cypress/src/jtag/drivers/kitprog3.c#L375).  The firmware seems to get the USB request OK but it reports it can not actually acquire the target chip.

**QUESTIONS**
* Will KP3_REQUEST_ACQUIRE in Kitprog3/Miniprog4 firmware work with CCG3PA?

**TODO**
* Determine if MiniProg4 is actually doing power-cycle mode where it removes and applies power on Vtarg pin (power to the CCG3PA).  Need to halt the target before making sysreq calls into the SROM... this is what KP3_REQUEST_ACQUIRE should be doing?
* Review how the code used to work in 2014 when CCG1 was added.  Vincent Palatin  from the ChromeOS team has replied to my email and confirmed the CCG1 worked with OpenOCD and STLINK/V2 and a FTDI FT2232.  Cypress later removed that support but I switch back to the older version of the repo.

**Comment by pdp7** [comment]
UPDATE: I was able to program CCG3PA from OpenOCD using MiniProg4 as follows:
```
pdp7@x1:~/dev/dojofive/bcd/openocd$ git diff
diff --git a/jimtcl b/jimtcl
--- a/jimtcl
+++ b/jimtcl
@@ -1 +1 @@
-Subproject commit 0aa0fb4e3a38d38a49de9eb585d93d63a370dcf6
+Subproject commit 0aa0fb4e3a38d38a49de9eb585d93d63a370dcf6-dirty
diff --git a/src/flash/nor/psoc4.c b/src/flash/nor/psoc4.c
index 405d452cdd32..7ccb12f23579 100644
--- a/src/flash/nor/psoc4.c
+++ b/src/flash/nor/psoc4.c
@@ -251,6 +251,7 @@ const struct psoc4_chip_family psoc4_families[] = {
        { 0xAB, "PSoC 4100S",                           .flags = 0, .spcif_ver = spcif_v3 },
        { 0xAC, "PSoC 4100PS/PSoC Analog Coprocessor",  .flags = 0, .spcif_ver = spcif_v3 },
        { 0xAE, "PSoC 4xx8 BLE",                        .flags = PSOC4_FLAG_IMO_NOT_REQUIRED, .spcif_ver = spcif_v2 },
+       { 0xB0, "CCG3PA USB Type-C Port Controller",    .flags = 0, .spcif_ver = spcif_v3 },
        { 0xB5, "PSoC 4100S Plus",                      .flags = 0, .spcif_ver = spcif_v3 },
        { 0xB8, "PSoC 4100S Plus/PSoC 4500",            .flags = 0, .spcif_ver = spcif_v3 },
        { 0xBE, "PSoC 4100S Max",                       .flags = 0, .spcif_ver = spcif_v3 },
pdp7@x1:~/dev/dojofive/bcd/openocd$ 
```
This PR #5 

Here are the results:
```
pdp7@x1:~/dev/dojofive/bcd/openocd$ openocd  -s tcl -f interface/kitprog3.cfg -f target/psoc4.cfg -c "kitprog3 power_config on 3300; kitprog3 acquire_config on 0r1 5; init; kitprog3 acquire_psoc; program CYPD3171-24LQXQ_cla.hex verify reset exit"
Open On-Chip Debugger 0.10.0+dev-gd526e667dedf-dirty (2021-02-22-17:17)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
adapter speed: 2000 kHz
** Auto-acquire enabled, use "set PSOC4_USE_ACQUIRE 0" to disable
cortex_m reset_config sysresetreq
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: JTAG Supported
Info : CMSIS-DAP: FW Version = 2.0.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : KitProg3: FW version: 2.10.878
Info : KitProg3: Pipelined transfers enabled
Info : kitprog3: powering up target device using KitProg3 (VTarg = 3300 mV)
Info : VTarget = 3.307 V
Info : kitprog3: acquiring the device...
Info : clock speed 2000 kHz
Info : Power dropout detected, running power_dropout proc.
Sensed power dropout.
Info : SWD DPIDR 0x0bb11477
Info : psoc4.cpu: hardware has 4 breakpoints, 2 watchpoints
*****************************************
** Silicon: 0x2003, Family: 0xB0, Rev.: 0x12 (A1)
** Detected Family: CCG3PA USB Type-C Port Controller
** Detected Main Flash size, kb: 64
** Chip Protection: protection OPEN
*****************************************
Info : starting gdb server for psoc4.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : kitprog3: acquiring the device...
Info : psoc4.cpu: external reset detected
Info : SWD DPIDR 0x0bb11477
Info : SWD DPIDR 0x0bb11477
Error: DP initialisation failed
Info : kitprog3: acquiring the device...
Info : SWD DPIDR 0x0bb11477
psoc4.cpu halted due to debug-request, current mode: Thread 
xPSR: 0xa1000000 pc: 0x1000003e msp: 0x20001fe8
** Device acquired successfully
** Programming Started **
auto erase enabled
Info : ignoring flash probed value, using configured bank size
[100%] [################################] [ Programming ]
Warn : no flash bank found for address 0x90300000
Warn : no flash bank found for address 0x90500000
Warn : no flash bank found for address 0x90600000
wrote 65600 bytes from file CYPD3171-24LQXQ_cla.hex in 1.789399s (35.801 KiB/s)
** Programming Finished **
** Verify Started **
verified 65600 bytes in 0.161609s (396.404 KiB/s)
** Verified OK **
** Resetting Target **
Info : SWD DPIDR 0x0bb11477
Info : SWD DPIDR 0x0bb11477
Error: DP initialisation failed
shutdown command invoked
Info : psoc4.dap: powering down debug domain...
Warn : Failed to power down Debug Domains
 ```
